import GEOPages from './GEOPages';
import EntityFacts from './EntityFacts';
import { geoRoutes } from '../lib/geo';
import { services, industries, cases, articles, titleFor } from '../lib/content';
import { FAQ } from './SEO';
import DemoForm from './DemoForm';
import Script from 'next/script';
import calculator from '../content/calculator.json';

function CTA(){return <section className="page-cta"><h2>Identifiez votre prochaine priorité.</h2><a className="button primary" href="/free-ai-visibility-audit">Demander mon audit gratuit ↗</a><a className="button" href="/book-call">Préparer un échange stratégique ↗</a></section>}
function Intro({label,title,text}:{label:string,title:string,text:string}){return <><p className="label">{label}</p><h1>{title}</h1><p className="page-intro">{text}</p></>}
function Cards({items}:{items:{title:string,intro:string,href:string}[]}){return <div className="page-grid">{items.map(x=><article className="page-card" key={x.href}><h2>{x.title}</h2><p>{x.intro}</p><a className="text-link" href={x.href}>Découvrir {x.title} ↗</a></article>)}</div>}
export default async function ContentPage({route,search}:{route:string,search:Record<string,string|string[]|undefined>}){
 if(geoRoutes.includes(route)||route==='glossary')return <GEOPages route={route}/>;
 const [group,slug]=route.split('/');
 let content:React.ReactNode;
 if(group==='services' && slug){const s=services.find(x=>x.slug===slug)!;content=<><Intro label="Services" title={s.title} text={s.intro}/><section className="direct-answer"><h2>Le besoin à traiter</h2><p>{s.context} {s.approach}</p></section><section className="page-section"><h2>Les actions possibles</h2><ul className="page-grid">{s.items.map(item=><li className="page-card" key={item}><h3>{item}</h3></li>)}</ul></section><section className="page-section"><h2>{s.context}</h2><p>{s.approach}</p><h2>Les indicateurs suivis</h2><p>{s.measurement}</p><p>Le périmètre, les livrables et les accès nécessaires sont convenus avant le lancement.</p></section><a className="text-link" href="/services">Tous les services</a></>}
 else if(route==='services'){content=<><Intro label="Nos services" title="Des expertises reliées à vos objectifs." text="Choisissez les actions utiles à votre visibilité, à vos demandes entrantes et à votre suivi commercial."/><Cards items={services.map(s=>({...s,href:'/services/'+s.slug}))}/><section id="solutions" className="page-section"><h2>Par quel besoin commencer ?</h2><div className="page-grid">{[['seo-audit','Audit SEO','Repérez ce qui freine votre visibilité dans les moteurs de recherche.'],['automation-audit','Audit d’automatisation','Identifiez un processus répétitif à tester sur un périmètre limité.'],['growth-strategy','Stratégie de croissance','Reliez les canaux, le budget et les indicateurs à vos priorités.']].map(([id,title,text])=><article id={id} className="page-card page-section" key={id}><h3>{title}</h3><p>{text}</p><a className="text-link" href="/contact">Définir le périmètre</a></article>)}</div><a className="button primary" href="/free-ai-visibility-audit">Audit gratuit de visibilité IA</a></section></>}
 else if(group==='industries' && slug){const item=industries.find(x=>x.slug===slug)!;content=<><Intro label="Secteurs" title={item.title} text={item.intro}/><p className="page-intro">{item.description}</p><div className="page-grid">{item.focus.map((focus,i)=><section className="page-card" key={focus}><p className="label">Priorité 0{i+1}</p><h2>{focus}</h2><p>Précisez les questions des acheteurs et les indicateurs utiles au secteur {item.title.toLowerCase()} avant de choisir vos actions.</p></section>)}</div><section className="page-section"><h2>Suivez le parcours de vos acheteurs.</h2><p>Nous examinons comment vos clients découvrent votre offre, la comparent et prennent contact. Puis nous choisissons les contenus, les canaux et les étapes à améliorer.</p><a className="text-link" href="/services">Découvrir les expertises</a></section><a className="text-link" href="/industries">Tous les secteurs</a></>}
 else if(route==='industries'){content=<><Intro label="Secteurs" title="Une approche adaptée à vos acheteurs." text="Votre marché et votre cycle de vente déterminent les priorités."/><Cards items={industries.map(i=>({...i,href:'/industries/'+i.slug}))}/></>}
 else if(group==='case-studies' && slug){const c=cases.find(x=>x.slug===slug)!;content=<><p className="demo-badge">Scénario fictif · Illustration</p><Intro label={c.client+' / '+c.category} title={c.title} text="Exemple fictif. Les chiffres ci-dessous ne sont pas des résultats clients vérifiés."/><dl className="page-metrics">{c.metrics.map(m=><div key={m.label}><dt>{m.label}</dt><dd>{m.value}</dd></div>)}</dl><div className="article-body">{[['Contexte',c.context],['Problème',c.problem],['Approche',c.strategy],['Résultats illustratifs',c.results]].map(([title,text])=><section key={title}><h2>{title}</h2><p>{text}</p></section>)}<p className="form-notice">{c.measurementNotes}</p></div><a className="text-link" href="/case-studies">Tous les exemples</a></>}
 else if(route==='case-studies'){content=<><Intro label="Exemples de missions" title="Comprendre la méthode par l’exemple." text="Ces scénarios et leurs chiffres sont fictifs. Ils illustrent la présentation d’une mission, pas des références clients."/><div className="page-grid">{cases.map(c=><article className="page-card" key={c.slug}><span className="demo-badge">Scénario fictif · Illustration</span><p className="label">{c.client} / {c.category}</p><h2>{c.title}</h2><dl className="page-metrics">{c.metrics.map(m=><div key={m.label}><dt>{m.label}</dt><dd>{m.value}</dd></div>)}</dl><a className="text-link" href={'/case-studies/'+c.slug}>Voir le scénario</a></article>)}</div></>}
 else if(group==='blog' && slug){const a=articles.find(x=>x.slug===slug)!;content=<><Intro label={a.category+' / Brouillon éditorial'} title={a.title} text={a.intro}/><p className="small-note">Texte en cours de validation. Auteur et date de publication à confirmer. <a href="/authors/editorial-profile">Statut de l’auteur</a> · <a href="/editorial-policy">Politique éditoriale</a></p><article className="article-body">{a.sections.map(s=><section key={s.heading}><h2>{s.heading}</h2><p>{s.text}</p></section>)}{a.sources.length>0 && <section><h2>Sources</h2><ul>{a.sources.map(s=><li key={s.url}><a href={s.url}>{s.title}</a></li>)}</ul></section>}</article><a className="text-link" href="/blog">Tous les articles</a></>}
 else if(route==='blog'){const filtered=search.category==='guides';content=<><Intro label="Analyses" title="Des repères pour décider." text="Des guides sur la visibilité, la mesure et l’automatisation. Textes en cours de validation."/><nav className="page-filter" aria-label="Catégories d’articles"><a href="/blog" aria-current={!filtered?'page':undefined}>Tous les articles</a><a href="/blog?category=guides" aria-current={filtered?'page':undefined}>Guides</a></nav><Cards items={articles.filter(a=>!filtered||a.category==='Guides').map(a=>({...a,href:'/blog/'+a.slug}))}/></>}
 else if(route==='about'){content=<><Intro label="À propos" title="Une méthode commune. Des priorités claires." text="Nous relions référencement, contenu et automatisation pour faciliter l’acquisition et le suivi de vos prospects."/><div className="page-grid">{[['Visibilité','Aidez vos acheteurs à trouver votre offre et à comprendre ce qui la distingue.'],['Conversion','Donnez aux visiteurs les informations et les étapes utiles pour prendre contact.'],['Mesure','Définissez un point de départ et des indicateurs qui permettent de choisir la suite.']].map(([title,text])=><section className="page-card" key={title}><h2>{title}</h2><p>{text}</p></section>)}</div><section className="page-section"><h2>Notre méthode</h2><p>Comprendre, prioriser, réaliser, mesurer : quatre étapes pour passer du diagnostic aux actions.</p><p className="form-notice">Cette version de revue attend la validation de l’identité de l’agence, de l’équipe et des références.</p></section></>}
 else if(route==='contact' || route==='book-call' || route==='free-ai-visibility-audit'){const kind=route==='contact'?'contact':route==='book-call'?'call':'audit';const careers=route==='contact' && search.subject==='careers';content=<><Intro label={careers?'Candidature':'Parlons de votre projet'} title={kind==='audit'?'Demandez votre audit de visibilité IA.':kind==='call'?'Préparez un échange stratégique.':careers?'Présentez votre candidature.':'Quel objectif souhaitez-vous atteindre ?'} text={kind==='audit'?'Indiquez votre site et vos priorités pour cadrer un premier diagnostic de visibilité.':kind==='call'?'Présentez votre objectif et les questions à aborder.':'Décrivez votre situation et laissez une adresse pour vous répondre.'}/><div className="page-grid"><section className="page-card"><h2>{kind==='audit'?'Votre site et vos priorités':'Vos coordonnées'}</h2><DemoForm kind={kind}/></section><section className="page-card"><h2>{kind==='call'?'Un échange ciblé':'La suite'}</h2><p>{kind==='call'?'Nous ferons le point sur vos objectifs, vos canaux actuels et la prochaine action utile.':'Une fois l’envoi disponible, votre demande permettra de préciser le besoin et les informations nécessaires.'}</p><p>{kind==='audit'?'Le périmètre et le délai de l’audit seront confirmés ensemble. Ce formulaire ne lance pas de scan automatique.':kind==='call'?'Le calendrier n’est pas connecté. Ce formulaire ne confirme aucun créneau.':careers?'Aucun poste ouvert n’est annoncé sur cette page.':'Le formulaire indique si l’envoi est disponible.'}</p></section></div></>}
 else if(route==='tools'){content=<><Intro label="Outils" title="Chiffrez un scénario de travail." text="Ajustez les hypothèses pour estimer un potentiel. Le calculateur ne mesure pas votre visibilité et ne prédit pas vos revenus."/><div dangerouslySetInnerHTML={{__html:calculator.html}}/><Script src="/legacy/09-calculator.js"/></>}
 else {content=<><Intro label="Glossaire" title="Des termes clairs pour mieux décider." text="Les notions utiles pour comprendre les services et leurs indicateurs."/><div className="page-grid">{[['SEO','Search Engine Optimization: improving the discoverability and understanding of pages in organic search.'],['GEO','Generative Engine Optimization: work aimed at representation and citation in generated answers, without guarantees.'],['AEO','Answer Engine Optimization: a working term for content designed to answer specific questions clearly.'],['AI Search','Search experiences using AI to interpret questions and compose responses.'],['CRO','Conversion Rate Optimization: testing improvements to the actions visitors take in a defined journey.'],['Attribution','A method of assigning credit for an outcome to touchpoints, subject to the data and model used.']].map(([term,text])=><section className="page-card" key={term}><h2>{term}</h2><p>{text}</p></section>)}</div><p>Pour approfondir : <a className="text-link" href="https://developers.google.com/search/docs/appearance/ai-features">Google Search Central</a></p></>}
 return <main id="content" className="editorial-page" tabIndex={-1}><nav className="breadcrumb" aria-label="Fil d’Ariane"><a href="/">Accueil</a> / {slug?<><a href={'/'+group}>{titleFor(group)}</a> / <span>{titleFor(route)}</span></>:<span>{titleFor(route)}</span>}</nav>{content}{route==='about' && <EntityFacts/>}<FAQ route={route}/><CTA/></main>;
}
