import {comparisons,terms,geoTitles,geoDescriptions} from '../lib/geo';
import authors from '../content/authors.json';
import {articles} from '../lib/content';
export default function GEOPages({route}:{route:string}){
 const comparison=comparisons.find(c=>'comparisons/'+c.slug===route);
 let body:React.ReactNode;
 if(comparison)body=<><section className="direct-answer"><h2>La différence en quelques mots</h2><p>{comparison.answer}</p></section><div className="comparison-table-wrap"><table><caption>Différences pratiques et limites</caption><thead><tr><th scope="col">Question</th><th scope="col">{comparison.left}</th><th scope="col">{comparison.right}</th></tr></thead><tbody>{comparison.rows.map(([label,left,right])=><tr key={label}><th scope="row">{label}</th><td>{left}</td><td>{right}</td></tr>)}</tbody></table></div><section className="page-section"><h2>Ce que cela change pour votre site</h2><p>{comparison.note}</p><p>Partez des questions de vos acheteurs, vérifiez les informations disponibles et définissez la méthode de mesure avant d’annoncer des progrès.</p><a className="text-link" href={comparison.source}>{comparison.sourceTitle}</a></section></>;
 else if(route==='comparisons')body=<div className="page-grid">{comparisons.map(c=><article className="page-card" key={c.slug}><h2>{c.title}</h2><p>{c.answer}</p><a className="text-link" href={'/comparisons/'+c.slug}>Lire le comparatif</a></article>)}</div>;
 else if(route==='glossary')body=<><dl className="page-grid">{terms.map(t=><div className="page-card" id={t.id} key={t.id}><dt><h2>{t.name}</h2></dt><dd>{t.definition}</dd></div>)}</dl><a className="text-link" href="/comparisons">Comparer SEO, GEO et AEO</a><p>Ces définitions précisent le sens des termes utilisés sur ce site. <a className="text-link" href="https://developers.google.com/search/docs/appearance/ai-features">Documentation Google Search Central</a></p></>;
 else if(route==='editorial-policy')body=<div className="article-body">{[
 ['Distinguer les preuves des exemples','Les résultats clients mesurés, les recherches et les scénarios fictifs doivent être identifiés. Un exemple de démonstration ne constitue pas une preuve de résultat.'],
 ['Citer des sources identifiables','Les explications techniques renvoient aux documentations ou recherches disponibles. Une règle propre à une plateforme ne s’applique pas automatiquement aux autres. Les sources sont revérifiées lors de la revue éditoriale.'],
 ['Identifier la personne responsable','Chaque article doit avoir un auteur ou un relecteur identifié et une date de validation. Ces informations restent à fournir pour les brouillons actuels. L’aide de l’IA ne remplace pas cette responsabilité.'],
 ['Rendre les mesures vérifiables','Un résultat client nécessite un point de départ, une période, un périmètre et une source. Une observation IA précise les questions, les plateformes, les langues et les dates. Une variation relative doit être distinguée d’un écart en points de pourcentage.']
 ].map(([title,text])=><section key={title}><h2>{title}</h2><p>{text}</p></section>)}<section><h2>Signaler une correction</h2><p>Utilisez la page de contact pour préciser le passage concerné et la source de votre correction. Le formulaire indique si l’envoi est disponible.</p><a className="text-link" href="/contact">Nous contacter</a></section></div>;
 else if(route==='authors')body=<><p>Aucune identité d’auteur n’a encore été validée. Le profil ci-dessous indique les informations à compléter ; il ne présente pas un membre de l’équipe.</p><a className="text-link" href="/authors/editorial-profile">Voir le statut du profil</a><a className="text-link" href="/editorial-policy">Lire la politique éditoriale</a></>;
 else {const author=authors[0];body=<><section className="direct-answer"><h2>Attribution à confirmer</h2><p>{author.name||'Auteur non renseigné.'} La biographie et les qualifications doivent être vérifiées avant publication.</p></section><section className="page-section"><h2>Articles en attente d’attribution</h2><ul>{articles.map(a=><li key={a.slug}><a className="text-link" href={'/blog/'+a.slug}>{a.title}</a></li>)}</ul></section><a className="text-link" href="/editorial-policy">Consulter les règles de validation</a></>}
 return <main id="content" className="editorial-page" tabIndex={-1}><nav className="breadcrumb" aria-label="Fil d’Ariane"><a href="/">Accueil</a> / {route.includes('/')&&<><a href={'/'+route.split('/')[0]}>{geoTitles[route.split('/')[0]]}</a> / </>}<span>{geoTitles[route]||'Glossaire'}</span></nav><p className="label">Méthode et repères</p><h1>{geoTitles[route]||'Des termes clairs pour mieux décider.'}</h1><p className="page-intro">{geoDescriptions[route]||'Les notions utiles pour comprendre nos services et leurs indicateurs.'}</p>{body}<section className="page-cta"><h2>Précisez vos priorités de visibilité.</h2><a className="button primary" href="/free-ai-visibility-audit">Demander mon audit gratuit</a></section></main>;
}
