export const comparisons = [
 {slug:'seo-vs-geo',title:'SEO et GEO : quelles différences ?',answer:'Le SEO vise la visibilité dans les résultats de recherche. Le GEO s’intéresse à la présence dans les réponses générées par l’IA. Les deux approches partagent des bases, sans garantir de position ni de citation.',rows:[['Objectif','Être trouvé dans les résultats naturels','Être représenté ou cité dans les réponses IA'],['Contenus','Pages utiles, structure claire et accès technique','Réponses précises, preuves et sources identifiables'],['Mesure','Impressions, clics et conversions définies','Mentions et citations dans un panel de questions documenté'],['Lien','Une base pour rendre les contenus accessibles','Une approche complémentaire au SEO']],left:'SEO',right:'GEO',source:'https://developers.google.com/search/docs/appearance/ai-features',sourceTitle:'Google Search Central — Fonctionnalités IA',note:'Pour les fonctionnalités IA de Google, les bases du SEO restent applicables. Aucun balisage propre à l’IA n’est requis pour être éligible.'},
 {slug:'geo-vs-aeo',title:'GEO et AEO : réponses, sources et points communs',answer:'Le GEO s’intéresse à la présence dans les réponses générées. L’AEO désigne ici le travail qui rend un contenu utile comme réponse directe. Ces notions se recoupent ; elles ne garantissent aucune diffusion.',rows:[['Priorité','La représentation et les citations dans les réponses IA','La clarté de la réponse à une question précise'],['Travail','Vérifier les sources, les preuves et la présence observée','Rédiger une réponse concise avec le contexte nécessaire'],['Mesure','Citations et mentions dans un échantillon défini','Utilité et présence de la réponse dans les formats étudiés'],['Limite','Aucune recommandation garantie','Aucun emplacement garanti']],left:'GEO',right:'AEO',source:'https://arxiv.org/abs/2311.09735',sourceTitle:'Aggarwal et al. — Generative Engine Optimization',note:'La recherche sur le GEO propose un cadre d’analyse, pas une garantie de résultat commercial. AEO est employé ici comme définition de travail.'}
];
export const terms=[
 {id:'seo',name:'SEO',definition:'Référencement naturel : améliorer la découverte et la compréhension des pages dans les moteurs de recherche.'},
 {id:'geo',name:'GEO',definition:'Travail sur la représentation et les citations d’une marque dans les réponses générées par l’IA, sans garantie de présence.'},
 {id:'aeo',name:'AEO',definition:'Terme employé ici pour désigner la rédaction de contenus qui répondent clairement à des questions précises.'},
 {id:'ai-search',name:'Recherche IA',definition:'Recherche utilisant l’IA pour interpréter une question et composer une réponse.'},
 {id:'cro',name:'CRO',definition:'Optimisation des conversions : tester des améliorations du parcours pour faciliter une action définie, comme une prise de contact.'},
 {id:'attribution',name:'Attribution',definition:'Méthode pour relier un résultat à des points de contact, dans les limites des données et du modèle retenu.'},
 {id:'citation',name:'Citation IA',definition:'Référence à une source dans une réponse générée. Une citation se distingue d’une mention sans lien et ne vaut pas recommandation.'},
 {id:'visibility-sample',name:'Panel de visibilité',definition:'Ensemble défini de questions, plateformes, langues et dates d’observation. Les résultats décrivent ce panel, pas toutes les réponses possibles.'}
];
export const geoRoutes=['comparisons',...comparisons.map(c=>'comparisons/'+c.slug),'editorial-policy','authors','authors/editorial-profile'];
export const geoTitles:Record<string,string>={comparisons:'Comparer SEO, GEO et AEO','editorial-policy':'Politique éditoriale',authors:'Auteurs et expertise','authors/editorial-profile':'Profil éditorial — attribution à confirmer',...Object.fromEntries(comparisons.map(c=>['comparisons/'+c.slug,c.title]))};
export const geoDescriptions:Record<string,string>={comparisons:'Comprenez les différences entre SEO, GEO et AEO, leurs points communs et leurs limites de mesure.','editorial-policy':'Notre cadre de validation des sources, des exemples et des résultats avant publication.',authors:'Les auteurs et leurs qualifications doivent être identifiés avant la publication des articles.','authors/editorial-profile':'Ce profil attend un nom, une biographie et des références vérifiables. Aucun auteur n’est attribué aux brouillons actuels.',...Object.fromEntries(comparisons.map(c=>['comparisons/'+c.slug,c.answer]))};
